### ISSUE TITLE
Search doesn't work by hitting enter

### ISSUE THREAD

**Issue by parvsablok** [MarCUS103/Weather_App#1]
It will be great if a function can be added of rather than clicking on the search icon we simply hit enter on keyboard to search. :)

**Comment by MarCUS103** [comment]
Will surely work on it. If you can resolve the issue and create a pull request for the same, it would be just amazing. 😄

**Comment by MarCUS103** [comment]
> It will be great if a function can be added of rather than clicking on the search icon we simply hit enter on keyboard to search. :)

Will surely work on it. If you can resolve the issue and create a pull request for the same, it would be just amazing. 😄
